### ISSUE TITLE
One container with common fileshare but with different directories in container

### ISSUE THREAD

**Issue by yuriipaneiko** [Azure-Samples/sftp-creation-template#10]
Is there any way to create one container with multiple users that will have access only to their own folders? But all data must be stored in one file share. I tried to do it myself, but it does not work.

**Comment by bhummerstone** [comment]
Yes, unfortunately Azure Files doesn't store/preserve the necessary permissions to allow this yet, so it would be a bit of a security risk. I believe they're working on something that might resolve this though :)

**Comment by yuriipaneiko** [comment]
@bhummerstone Ok,thx, don't you know - is it possible to use blob storage, instead of fileshare?

**Comment by bhummerstone** [comment]
You may be able to do this using the new NFS support on Azure Blob, as that should preserve the ACLs: https://azure.microsoft.com/en-us/blog/nfs-30-support-for-azure-blob-storage-is-now-in-preview/ 

You'll probably need to modify the container image to include the necessary NFS mount commands, but definitely worth investigating
