### ISSUE TITLE
NSG on container access

### ISSUE THREAD

**Issue by schemert15** [Azure-Samples/sftp-creation-template#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I activated the sftp in the container and it works, but its open to the world. 
As my source will be sending from 1 specific IP address I would like to only  open that IP to the public url. 
Is there a way to assign an NSG to this container?

Have not yet worked with containers on Azure yet, sorry.

Thanks for your help
Sander

**Comment by bhummerstone** [comment]
Not yet, unfortunately: there's a scenario with vNet integration using an Azure Load Balancer that should make this work, but it isn't quite there yet: https://docs.microsoft.com/en-us/azure/load-balancer/backend-pool-management#configure-backend-pool-by-ip-address-and-virtual-network

What I have managed to get working is deploying an nginx container in the same ACI Container Group as a proxy for the SFTP container; gist is here: https://gist.github.com/bhummerstone/286300e7eca065cccdeaf853e5b98117

The idea here is that you create a custom nginx container with the public IPs in a configuration file, and then use that in the same ACI.

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
