### ISSUE TITLE
Add a way to store and authenticate against SSH public keys

### ISSUE THREAD

**Issue by nexxai** [Azure-Samples/sftp-creation-template#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> n/a

### Any log messages given by the failure
> n/a

### Expected/desired behavior
> n/a

### OS and Version?
> n/a

### Versions
> n/a

### Mention any other details that might be useful

Adding a method to use public key authentication should be the standard in the year 2020.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bhummerstone** [comment]
Take a look here: https://github.com/Azure-Samples/sftp-creation-template/issues/2

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
