### ISSUE TITLE
How to add ssh

### ISSUE THREAD

**Issue by r3dr4gon** [Azure-Samples/sftp-creation-template#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Is there any way to add ssh to this sftp? I saw it is possiable with this container, but I'm not sure how to adjest it to the arm template.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bhummerstone** [comment]
@r3dr4gon do you mean using SSH keys for authentication?

**Comment by r3dr4gon** [comment]
@bhummerstone Yes I'm, sorry for being unclear.

somthing like "Providing your own SSH host key (recommended)" in the [docker examples](https://hub.docker.com/r/atmoz/sftp). thanks.

**Comment by bhummerstone** [comment]
Gotcha. Check out my example of that here: https://github.com/bhummerstone/azure-templates/blob/master/compute/sftp/sftp-config-file.json

The key is creating another file share (this template does that) and mounting it to the user directory

**Comment by r3dr4gon** [comment]
@bhummerstone amazing :) sounds like that implement what i had in mind. Cheers 👍

**Comment by srusru** [comment]
@r3dr4gon can you provide the script you have. TIA

**Comment by r3dr4gon** [comment]
@srusru what script? the arm template? If so it is basically a copy of what @bhummerstone posted here: https://github.com/bhummerstone/azure-templates/blob/master/compute/sftp/sftp-config-file.json
are you having any trouble with it? do notice that it will only update the ssh keys when they are already in the blob storage,i.e., if the sftp is up and no keys in the blob storage you will have to upload your keys then restart the sftp container.

**Comment by oppknox** [comment]
@bhummerstone I need to create another user that can authenticate with an SSH key. The repository you link appears to be no longer public. Are you able to still share? Thank you!

**Comment by bhummerstone** [comment]
Apologies, I did a bit of re-organising of my repo!

Here's a sample with multiple users: https://github.com/bhummerstone/azure-templates/blob/master/arm/compute/sftp/sftp-existing-stg-multi-user.json

Here's an example mounting in the config file: https://github.com/bhummerstone/azure-templates/blob/master/arm/compute/sftp/sftp-config-file.json
