### ISSUE TITLE
I want to remove /upload directory while deploying SFTP in azure container instance.

### ISSUE THREAD

**Issue by ninadbalang** [Azure-Samples/sftp-creation-template#20]
I don't want default home directory /upload. I tried to remove while deploying template but its not working.

**Comment by bhummerstone** [comment]
Have a look here: https://github.com/Azure-Samples/sftp-creation-template/issues/4

**Comment by jshsec** [comment]
Hi, I have the same issue here. Except I cannot use the solution laid out in #4. Is there any other solution through editing the template?

**Comment by bhummerstone** [comment]
Since this is part of the inbuilt SSH configuration, there isn't much else you can do unfortunately.

Is there a particular reason you can't use the other workaround?

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
