### ISSUE TITLE
sftp-creation-template -queries - feature - configuration

### ISSUE THREAD

**Issue by mimanu** [Azure-Samples/sftp-creation-template#21]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
1.	Can we add another user for the sftp?
2.	I will need to create 6 sftp aci instance – will there be effect or conflict on the naming on the group?
3.	Can I reuse the fileshare name? as here will be 6 created but different ACI
4.	Is it ok to have random storagename account?
5.	I’ve tried to re-run the template for another deployment seems is just detect the previous deployment and didn’t create a new one
6. Can use private network as well?

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bhummerstone** [comment]
Number of questions here!

1. Check out #7 
2. Change the sftpContainerGroupName variable for each one to avoid conflicts
3. You can reuse the same file share name in different storage accounts
4. Yes, and it is more likely to avoid conflicts as the account name must be globally unique
5. Which specific template: with or without creating a storage account?
6. If you are only accessing the ACI from internal networks, then yep!

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
