### ISSUE TITLE
Multiple Users in SFTP server.

### ISSUE THREAD

**Issue by syedyakoobali** [Azure-Samples/sftp-creation-template#22]
https://docs.microsoft.com/en-us/samples/azure-samples/sftp-creation-template/sftp-on-azure/

I have gone through the above article to create an SFTP server in azure. My concern here is that I want to give access to multiple users. How can I create multiple users and how can I assign passwords to them. Thanx

**Comment by ltkvien** [comment]
Hi, see it here https://github.com/Azure-Samples/sftp-creation-template/issues/7

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
