### ISSUE TITLE
fileshare is created with default space 5tb, which is a lot, can we provide space in the template while creating fileshare/sftp?

### ISSUE THREAD

**Issue by mdmtoolkit** [Azure-Samples/sftp-creation-template#24]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bhummerstone** [comment]
Yes, this is possible. You would need to edit the template [here](https://github.com/Azure-Samples/sftp-creation-template/blob/master/create-aci-sftp-server-and-azure-files/azuredeploy.json#L105) and add a new parameter for quota and provide the value.

For example, you could add a couple of lines such as:
"--quota",
"100"
for a quota of 100GB

**Comment by mdmtoolkit** [comment]
> Yes, this is possible. You would need to edit the template [here](https://github.com/Azure-Samples/sftp-creation-template/blob/master/create-aci-sftp-server-and-azure-files/azuredeploy.json#L105) and add a new parameter for quota and provide the value.
> 
> For example, you could add a couple of lines such as:
> "--quota",
> "100"
> for a quota of 100GB

Great! Thanks!!

**Comment by mdmtoolkit** [comment]
Closing as it was resolve.
