### ISSUE TITLE
Can someone please add the template for utilizing SSH instead of password?

### ISSUE THREAD

**Issue by oppknox** [Azure-Samples/sftp-creation-template#28]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

I see ATOMZ allows for the use of SSH, but I dont understand the container space well. Seeking template to utilize SSH over password. https://hub.docker.com/r/atmoz/sftp Thank you!

It seems that someone has posted an example previously but it did not make it was on a personal repository and now doesnt appear exist. https://github.com/bhummerstone/azure-templates/blob/master/compute/sftp/sftp-config-file.json

**Comment by oppknox** [comment]
closing as this guy is a saint

https://charbelnemnom.com/how-to-deploy-sftp-service-on-microsoft-azure/#Logging_in_with_SSH_keys

**Comment by bhummerstone** [comment]
Sorry, I did some re-organisation of my repository and broke the links!

Here's a Bicep version of the template w/ SSH keys: https://github.com/bhummerstone/azure-templates/blob/master/bicep/compute/sftp/sftp-ssh-keys.bicep

Also +1 to Charbel being a saint ;)

**Comment by oppknox** [comment]
Thanks for sharing our version! Learning from both will is helpful.

**Comment by CharbelNemnom** [comment]
> Sorry, I did some re-organisation of my repository and broke the links!
> 
> Here's a Bicep version of the template w/ SSH keys: https://github.com/bhummerstone/azure-templates/blob/master/bicep/compute/sftp/sftp-ssh-keys.bicep
> 
> Also +1 to Charbel being a saint ;)

Many Thanks, Ben for your hard work as well! Yes, Charbel is a saint name ;)
