### ISSUE TITLE
Multiple Users Issue

### ISSUE THREAD

**Issue by somuworld** [Azure-Samples/sftp-creation-template#29]
I know this was discussed in earlier threads but I got confused with multiple dicsussions in each thread. I was able to create ACI and Fileshare using the template provided. I would like to create multiple users to use same fileshare, the scenario is that user1 will drop the files in SFTP location and user2 will read the files copied by user1.

I tried Export template> Deploy> Edit template> (Modify environment variable to add new user) but this resulted in  below error:
{
    "status": "Failed",
    "error": {
        "code": "InvalidStorageAccountKey",
        "message": "The Azure storage account key in volume 'sftpvolume' is invalid."
    }
}

Also, if I have to edit the image and redeploy to place the users list in /etc/sftp/users.conf, could you help with the steps.

![image](https://user-images.githubusercontent.com/13004966/131748021-56bd2525-6c03-4fea-8dc3-4877311845aa.png)

**Comment by bhummerstone** [comment]
Exporting the template from the Azure Portal doesn't export the Storage Account keys: you'd need to update the original template you used to deploy and re-deploy.

Also, if you add multiple users, by default they get different home directories and are forced just to their home directory, so you would need to mount a "common" file share and then add a custom mount for each user; there's a good example from the original creator of the container image here: https://github.com/atmoz/sftp#execute-custom-scripts-or-applications

So the steps would be:
- Create a script to mount a shared drive to a common location (e.g. from /mnt/common to /home/user1/common and /home/user2/common)
- Create a new container image with this script included, and upload to Docker Hub or Azure Container Registry
- Modify your ARM template to point to this new container image
- Modify the SFTP_USERS environment variable to be "user1:password1:::upload user2:password2:::upload" (note the space to separate the users)
- Add a new Azure File share mount to the common location (e.g. /mnt/common from the example above)

Hope this helps!

**Comment by bhummerstone** [comment]
Closing this issue as it has been dormant for a while; let me know if you still need some help with this
