### ISSUE TITLE
This article needs to be updated to reflect the new native SFTP service in Azure.

### ISSUE THREAD

**Issue by Mike-Crowley** [Azure-Samples/sftp-creation-template#31]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>the statement "In absence of a fully managed service" and overall sentiment of this article should reflect the presence of the new SFTP service for Azure Blob storage: https://docs.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>in reference to live documentation, posted here: https://docs.microsoft.com/en-us/samples/azure-samples/sftp-creation-template/sftp-on-azure/

**Comment by bhummerstone** [comment]
I have put a note just under that wording, but I'll update it to remove that sentence

**Comment by bhummerstone** [comment]
Done! https://github.com/Azure-Samples/sftp-creation-template/commit/c72bba85abef29bd5900190690358fc443dea463
