### ISSUE TITLE
Cannot upload to root of SFTP Service

### ISSUE THREAD

**Issue by aradice-truenorth** [Azure-Samples/sftp-creation-template#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Start up the SFTP Service
2. Attempt to upload files to the root of the SFTP service (used WinSCP)
3. Permissions error.

### Any log messages given by the failure
> Permission denied.
> Error code: 3
> Error message from server: Permission denied

### Expected/desired behavior
> No permissions error, able to upload to the root of the SFTP service.

### OS and Version?
> Windows 10 client.

### Versions
>Commit bd437a09cb21936310029743130fa0f40316d3e2of amoz/sftp git repo

### Mention any other details that might be useful
What I really want is for the root of the SFTP service to be the Azure file share so the root is writeable AND any files written to it end up in the backing Storage Account.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by bhummerstone** [comment]
Hi! If you modify the template to remove the "/upload" from the volume mount section, does that meet your requirement?

For example:

```
"volumeMounts": [
    {
         "mountPath": "[concat('/home/', parameters('sftpUser'))]",
         "name": "sftpvolume",
         "readOnly": false
    }
]
```

**Comment by aradice-truenorth** [comment]
> Hi! If you modify the template to remove the "/upload" from the volume mount section, does that meet your requirement?
> 
> For example:
> 
> ```
> "volumeMounts": [
>     {
>          "mountPath": "[concat('/home/', parameters('sftpUser'))]",
>          "name": "sftpvolume",
>          "readOnly": false
>     }
> ]
> ```

Thank you @bhummerstone , I have tried that; I am then unable to connect to the SFTP service, though when I connect to the container all the same processes seem to be running.

**Comment by bhummerstone** [comment]
Gotcha: probably because you have mounted the Files share over the user's home directory!

Might be better to just change this from the SFTP client perspective, for example: https://www.digitalocean.com/community/questions/changing-default-directory-on-sftp-login

**Comment by aradice-truenorth** [comment]
> Might be better to just change this from the SFTP client perspective, for example: https://www.digitalocean.com/community/questions/changing-default-directory-on-sftp-login

Unfortunately configuring the sftp client isn't an option. The sftp client in this case is some embedded software on a black box piece of hardware that is only capable of uploading to the root of the sftp service.

I could run usermod or modify the container ins some other way. Any tips with doing that?

**Comment by bhummerstone** [comment]
Done a bit of research, and you might be able to do this by modifying the default sshd_config provided with the container image to change ChrootDirectory to /upload instead: https://github.com/atmoz/sftp/blob/master/files/sshd_config

**Comment by bhummerstone** [comment]
You'd need to create a new container image with this new config, and then modify the ARM template sample to use your new image instead; this could be on Docker Hub or somewhere else e.g. Azure Container Registry

**Comment by aradice-truenorth** [comment]
Hello @bhummerstone I did something similar to what you suggested, I created a new container image with a slightly modified sshd_config, but the line I changed was the ForceCommand rather than the ChrootDirectory:

`ForceCommand internal-sftp -d /upload`

**Comment by bhummerstone** [comment]
Heya: is it OK to close off this issue now? Sounds like you came up with a good solution :)

**Comment by aradice-truenorth** [comment]
> Hello @bhummerstone I did something similar to what you suggested, I created a new container image with a slightly modified sshd_config, but the line I changed was the ForceCommand rather than the ChrootDirectory:
> 
> `ForceCommand internal-sftp -d /upload`

Happy to close this issue as the workaround does what I need.

**Comment by themizmd79** [comment]
@aradice-truenorth I have a similar issue unable to upload files in the root directory deployed using SFTP ACI.
How did i execute ForceCommand internal-sftp -d /upload for an existing container or if it's not possible please advice how will deploy with a new ACI. I have used https://raw.githubusercontent.com/mutazn/Azure-sftp-templates/main/sftp-existing-stg-multi-users.json to deploy SFTP users.

**Comment by bhummerstone** [comment]
You would need to modify the base image, upload a new container image, then re-deploy your ACI with the new image.

There are some steps here for creating a new image: https://github.com/Azure-Samples/sftp-creation-template/issues/3#issuecomment-517667440

Also, you can re-use the same Storage Account, so there would only be a small downtime whilst you replaced the front-end SFTP container :)
