### ISSUE TITLE
Monitoring the SFTP

### ISSUE THREAD

**Issue by r3dr4gon** [Azure-Samples/sftp-creation-template#6]
Is there a way to monitor the health of the sftp server in azure? other then looking on the on the container metrics?

**Comment by bhummerstone** [comment]
Hi! I think that the best way to do this is to use Azure Monitor to grab the container logs: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-log-analytics

You can then set alerts on specific log events: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-overview

**Comment by bhummerstone** [comment]
That said, if you encounter an error it may just be easier to redeploy the ACI running the SFTP server :)

**Comment by bhummerstone** [comment]
Closing this issue as it has been idle for a while
